### ISSUE TITLE
API permission override

### ISSUE THREAD

**Issue by bjendres** [veda-consulting-company/uk.co.vedaconsulting.outlookapi#63]
The extension uses the ``civicrm_alterAPIPermissions`` hook to alter the permissions for the ``activity`` and the ``domain`` entity. This, however, is done in a way that overwrites any changes (to other actions) added by other extensions.

**Comment by MegaphoneJon** [comment]
I just reviewed this code and it's a common-sense improvement.  Recommend a merge!
